### ISSUE TITLE
Feature: Pass a string or an array of keywords 

### ISSUE THREAD

**Issue by mischah** [sindresorhus/npm-keyword#12]
This would at least a way to workaround the API limit of 250 maximum results like described [here](https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#get-v1search).

Plus this would actually be needed to fix https://github.com/yeoman/yo/issues/544 in a sane way.

I would love to work on this if you accept that feature request and #11 is merged.

Cheers, Michael

**Comment by sindresorhus** [comment]
Yes, sounds useful.
