### ISSUE TITLE
Is it possible to specify a max number of returned libs

### ISSUE THREAD

**Issue by pketh** [sindresorhus/npm-keyword#8]
Maybe an optional count to return param, something like?

```
npmKeyword('gulpplugin', 5).then(packages => {
    console.log(packages);
    //=> array of length 5 [{name: 'gulp-autoprefixer', description: '...'}, ...]
});
```

**Comment by sindresorhus** [comment]
I don't think it's possible to specify that in the server request, but I would be open to a pull request that adds a streaming API.
