### ISSUE TITLE
Need to update search endpoint

### ISSUE THREAD

**Issue by mischah** [sindresorhus/npm-keyword#9]
Hej,

the endpoint used by that module is returning timeout errors frequently and will be probably be retired soon.

This is the feedback I got from npm support regarding https://github.com/yeoman/yo/issues/544.

> Thanks for reaching out. I've reached out to our team. They are in the process of retiring all endpoints as there are performance issues and timeouts. Per our team, you could run the below curl command instead:
> 
>     curl -XGET https://registry.npmjs.org/-/v1/search?text=keywords:yeoman-generator | json
> 
> For more information on the new search API, please go to:
> https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#get-v1search
> 
> Please let us know if there is anything else we can do for you. We’ll be here to help. Thank you. 

Problem with the new endpoint is that the result set is limited to a maximum of 250 😞 
That means for getting all yeoman generators (6984) we would need to call that endpoint almost 30 times 🙀 

Maybe the npms.io API offers an alternative endpoint to get all results with just one request.

**Comment by sindresorhus** [comment]
Yeah, the `npms.io` API is a better choice: https://api-docs.npms.io

I won't have time to do this, but pull request welcome :)

**Comment by mischah** [comment]
Would love to tackle this. Hope to find time within this or next week.

**Comment by mischah** [comment]
mhmm. the npms.io API search endpoint also has a size limit of 250 🙈 

> size | string | The total number of results to return (max of 250) 
> -- | -- | --

See https://api-docs.npms.io/#api-Search

**Comment by mischah** [comment]
Not that problematic. If a user searches for something that has more results they will have problems to get through a list of 250. So I guess there is no need to show them more.

**Comment by mischah** [comment]
@sindresorhus Is it okay to do the ES6ification within this PR?

Would include syntactic changes and getting rid if `pinkie-promise`.

**Comment by sindresorhus** [comment]
Easier if I just do that first. Gimme a few minutes.

**Comment by sindresorhus** [comment]
Done :)

**Comment by mischah** [comment]
Cool 🦄 
Thanks.
